@startuml
start

:Відкрити сторінку "Мої пристрої";
:Натсинути кнопку "Додати пристрій";
:Відкриття модального вікна;

partition "Крок 1: Пошук пристрою" {
  :Натиснути "Пошук пристрою";
  :Сканування BLE пристроїв;
  :Відображення списку пристроїв;
  :Обрати пристрій;
  if (Підключення успішне?) then (так)
    :Відобразити назву підключеного пристрою;
    :Активувати кнопку "Наступний крок";
  else (ні)
    :Виведення повідомлення про помилку;
    stop
  endif
}

partition "Крок 2: Сканування Wi-Fi" {
  :Надіслати запит на сканування мереж;
  :Відобразити список мереж;
  :Обрати мережу;
  :Натиснути кнопку "Наступний крок";
}

partition "Крок 3: Підключення до Wi-Fi" {
  :Ввести пароль;
  :Натиснути кнопку "Підключитись";
  :Надіслати SSID і пароль на пристрій;
  if (Підключення до Wi-Fi успішне?) then (так)
    :Очікувати на реєстрацію пристрою;
    if (Реєстрація успішна?) then (так)
      :Надіслати запит на приєднання пристрою до акаунту;
      if (Приєднанян успішне?) then (так)
        :Відображення повідомлення про успіх;
      else (ні)
        :Виведення повідомлення про помилку;
        stop
      endif
    else (ні)
      :Виведення повідомлення про помилку;
      stop
    endif
  else (ні)
    :Виведення повідомлення про помилку;
    stop
  endif
}

stop

@enduml
