@startuml

actor Користувач
boundary "Клієнт React PWA" as Client
control "Web Bluetooth API" as WebAPI
entity "Апаратний модуль ESP32" as ESP
entity "Wi-Fi Мережа" as WiFi
control "Сервер Node.js" as Server

== Пошук та підключення пристрою ==
Користувач -> Client : Натиснути кнопку "Додати пристрій"
Client -> WebAPI : Почати сканування BLE-пристроїв
WebAPI --> Client : Повернути список доступних BLE-пристроїв
Користувач -> Client : Натиснути на пристрій Clear Zone
Client -> WebAPI : Надіслати запит на підключення до пристрою
WebAPI -> ESP : Надіслати запит на підключення до пристрою
ESP --> WebAPI : Надіслати повідомлення про статус підключення
WebAPI --> Client : Надіслати повідомлення про статус підключення
Client ->> Користувач : Відобразити назву пристрою та статус підключення

== Пошук Wi-Fi мереж ==
Client -> WebAPI : Надіслати запит на пошук Wi-Fi мереж
WebAPI -> ESP : Надіслати запит на пошук Wi-Fi мереж
ESP -> WiFi : Надіслати запит на пошук Wi-Fi мереж
WiFi --> ESP : Надіслати список доступних мереж
ESP --> WebAPI : Надіслати список доступних мереж
WebAPI --> Client : Надіслати список доступних мереж
Client ->> Користувач : Відобразити список доступних мереж

== Підключення до Wi-Fi мережі ==
Користувач -> Client : Обрати мережу та ввести пароль
Client -> WebAPI : Надіслати SSID та пароль
WebAPI -> ESP : Надіслати SSID та пароль
ESP -> WiFi : Надіслати запит на підключення
WiFi --> ESP : Надіслати повідомлення про статус підключення
ESP -> Server : Надіслати запит на реєстрацію пристрою в системі
Server --> ESP : Надіслати повідомлення про статус реєстрації
ESP --> WebAPI : Надіслати повідомлення про статус реєстрації
WebAPI --> Client :  Надіслати повідомлення про статус реєстрації
Client -> Server :  Надіслати запит на приєднання пристрою до акаунту користувача
Server --> Client :   Надіслати повідомлення про статус реєстрації
Client ->> Користувач :   Надіслати повідомлення про статус реєстрації
@enduml
