@startuml
start

:Періодична перевірка якості повітря;

:Отримати поточну IAQ оцінку;
:Отримати IAQ оцінку за попередній період;

if (Дані доступні?) then (так)
  :Порівняти поточну та попередню IAQ оцінки;

  if (Якість повітря погіршилась?) then (так)
    :Перевірити, чи увімкнені сповіщення про погіршення;
    :Перевірити cooldown;

    if (Можна надіслати сповіщення?) then (так)
      :Надіслати push сповіщення\nпро погіршення якості повітря;
      :Оновити час останнього сповіщення;
    else (ні)
      :Не надсилати сповіщення;
    endif

  elseif (Якість повітря покращилась?) then (так)
    :Перевірити, чи увімкнені сповіщення про покращення;
    :Перевірити cooldown;

    if (Можна надіслати сповіщення?) then (так)
      :Надіслати push сповіщення\nпро покращення якості повітря;
      :Оновити час останнього сповіщення;
    else (ні)
      :Не надсилати сповіщення;
    endif

  else (ні)
    :Значної зміни IAQ немає;
  endif

else (ні)
  :Пропустити перевірку;
endif

stop
@enduml